[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]

[rpc_endpoints]
rinkeby = "${RINKEBY_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
rinkeby = { key = "${ETHERSCAN_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config